# Generated by Django 5.0.6 on 2024-06-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Accepted', 'Accepted')], max_length=50),
        ),
    ]
