# Generated by Django 5.0.6 on 2024-06-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='featured',
        ),
    ]
