# Generated by Django 5.0.6 on 2024-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_paymentsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='number',
            field=models.CharField(default=0, max_length=889),
            preserve_default=False,
        ),
    ]
