# Generated by Django 5.0.6 on 2024-06-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_userprofile_address_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
