# Generated by Django 5.0.6 on 2024-06-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_paymentsystem_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.paymentsystem'),
        ),
    ]
