# Generated by Django 5.0.6 on 2024-06-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('Yetkazilmoqda', 'Yetkazilmoqda'), ('Yatkazildi', 'Yatkazildi'), ('Tolov qilinmagan', 'Tolov qilinmagan')], max_length=50),
        ),
    ]
