# Generated by Django 5.0.6 on 2024-06-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_userprofile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='book',
            name='popular',
        ),
    ]
