# Generated by Django 5.0.6 on 2024-06-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_book_featured_remove_book_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
