# Generated by Django 5.0.6 on 2024-07-03 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
