# Generated by Django 5.0.6 on 2024-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='books',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
