# Generated by Django 5.0.6 on 2024-07-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='messages_sent',
            field=models.IntegerField(default=0),
        ),
    ]
