# Generated by Django 5.0.6 on 2024-07-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_cart_cartitem_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
