# Generated by Django 5.0.6 on 2024-07-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_remove_cartitem_cart_remove_cartitem_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_free_book', models.BooleanField(default=False)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('other_reward', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
