# Generated by Django 5.0.6 on 2024-07-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='is_free_book',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='other_reward',
        ),
        migrations.AddField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gifts/'),
        ),
    ]
