# Generated by Django 5.0.6 on 2024-07-12 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_remove_gift_discount_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date_won', models.DateField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.gift')),
            ],
        ),
    ]
