# Generated by Django 5.0.6 on 2024-07-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
