# Generated by Django 5.0.6 on 2024-07-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_promocode_usage_count_promocode_usage_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='type',
            field=models.CharField(choices=[('promo_code', 'Promotional Code'), ('free_book', 'Free Book')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
