# Generated by Django 5.0.6 on 2024-07-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_gift_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='type',
        ),
    ]
