# Generated by Django 5.0.6 on 2024-07-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_remove_gift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='type',
            field=models.CharField(choices=[('promo_code', 'Промокод'), ('free_book', 'Бесплатная книга')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
