# Generated by Django 5.0.6 on 2024-07-13 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_gift_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(related_name='favorite_books', to='shop.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.telegramuser')),
            ],
        ),
    ]
